config/routes.rb
Bundlr::Engine.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :projects

  root to: 'sessions#new'

  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/edit', to: 'users#edit'
  match '/home', to: 'users#show'

  

end

app/models/bundlr/project.rb
# == Schema Information
#
# Table name: bundlr_projects
#
#  id         :integer          not null, primary key
#  title      :string(255)
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

module Bundlr
  class Project < ActiveRecord::Base
    attr_accessible :title

    belongs_to :user

    validates :user_id, presence: true
    validates :title, length: { maximum: 15 }
    
    default_scope order: 'bundlr_projects.created_at DESC'
  end
end

app/models/bundlr/user.rb
# == Schema Information
#
# Table name: bundlr_users
#
#  id                  :integer          not null, primary key
#  email               :string(255)
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#  password_digest     :string(255)
#  remember_token      :string(255)
#  avatar_file_name    :string(255)
#  avatar_content_type :string(255)
#  avatar_file_size    :integer
#  avatar_updated_at   :datetime
#

module Bundlr
  class User < ActiveRecord::Base
    attr_accessible :email, :password, :password_confirmation, :avatar
    has_secure_password
    has_many :projects

    has_attached_file :avatar, styles: {
        thumb: '100x100>',
        square: '200x200#',
        medium: '300x300>'
    }

    before_save { |user| user.email = email.downcase }
    before_save :create_remember_token

    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
    validates :password, presence: true, length: { minimum: 6 }
    validates :password_confirmation, presence: true
    after_validation { self.errors.messages.delete(:password_digest) }

    private
        def create_remember_token
            self.remember_token = SecureRandom.urlsafe_base64
        end
        
  end
end

app/controllers/bundlr/application_controller.rb
module Bundlr
  class ApplicationController < ActionController::Base
  	protect_from_forgery
  	include SessionsHelper

  	# Force Signout to prevent CSRF Attacks
  	def handle_unverified_request
  		sign_out
  		super
  	end

  end
end

app/controllers/bundlr/projects_controller.rb
require_dependency "bundlr/application_controller"

module Bundlr
  class ProjectsController < ApplicationController

  	def index
  		@myprojects = current_user.projects
  		@allprojects = Project.all
  		@project = Project.new 
  	end

    def create
    	@project = Project.new(params[:project])
    	if @project.save
        	flash[:success] = "Welcome to the Sample App"
        	redirect_to home_path
    	end
    end

  end
end

app/controllers/bundlr/sessions_controller.rb
require_dependency "bundlr/application_controller"

module Bundlr
  class SessionsController < ApplicationController

  	def new
  	end

  	def create
  		user = User.find_by_email(params[:session][:email].downcase)
  		if user && user.authenticate(params[:session][:password])
  			sign_in user
        redirect_back_or user
  		else
  			flash.now[:error] = "Invalid email/password combo"
  			render 'new'
  		end
  	end

  	def destroy
  		sign_out
  		redirect_to signin_path
  	end

  end
end

app/controllers/bundlr/users_controller.rb
require_dependency "bundlr/application_controller"

module Bundlr
  class UsersController < ApplicationController
    before_filter :signed_in_user, only: [:edit, :update]
    before_filter :correct_user, only: [:edit, :update]

  	def show
  		@user = User.find(current_user.id)
  	end

    def new
    	@user = User.new
    end

    def edit
      @user = User.find(params[:id])
    end

    def update
      @user = User.find(params[:id])
      if @user.update_attributes(params[:user])
        flash[:success] = "User Updated"
        sign_in @user
        redirect_to @user
      else
        render 'edit'
      end
    end

    def create
    	@user = User.new(params[:user])
    	if @user.save
    		sign_in @user
        flash[:success] = "Welcome to the Sample App"
    		redirect_to @user
    	else
    		render 'new'
    	end
    end

      private

        def signed_in_user
          unless signed_in?
            store_location
            redirect_to signin_url, notice: "Please Sign In"
          end
        end

        def correct_user
          @user = User.find(params[:id])
          redirect_to(root_path) unless current_user?(@user)
        end
    
  end
end

 Mess+Noise, All I Do is Listen, Pedestrian.TV, Line of Best Fit & FBi's blog

app/helpers/bundlr/application_helper.rb
module Bundlr
  module ApplicationHelper
  end
end

app/helpers/bundlr/projects_helper.rb
module Bundlr
  module ProjectsHelper
  end
end

app/helpers/bundlr/sessions_helper.rb
module Bundlr
  module SessionsHelper

  	def sign_in(user)
  		cookies.permanent[:remember_token] = user.remember_token
  		self.current_user = user
  	end

  	def sign_out
  		self.current_user = nil
  		cookies.delete(:remember_token)
  	end

  	def signed_in?
  		!current_user.nil?
  	end

  	def current_user=(user)
  		@current_user = user
  	end

  	def current_user
  		@current_user ||= User.find_by_remember_token(cookies[:remember_token])
  	end

    def current_user?(user)
      user == current_user
    end

    def redirect_back_or(default)
      redirect_to(session[:return_to] || default)
      session.delete(:return_to)
    end

    def store_location
      session[:return_to] = request.url
    end

  end
end

app/helpers/bundlr/users_helper.rb
module Bundlr
  module UsersHelper
  end
end

app/views/bundlr/projects/index.html.erb
My Projects </br>

<% if @myprojects.count < 1 %>
	You have no projects.  Create one!
<% else %>
	<%= @myprojects %> </br>
<% end %>

</br>
</br>


All Projects </br>
<% if @allprojects.count < 1 %>
	There are no projects.  Create one!
<% else %>
	<%= @allprojects %> </br>
<% end %>

</br>

New Project<br/>

<%= form_for(@project) do |f| %>
	<%= f.text_field :title %>
	<%= f.submit "submit!" %>
<% end %>


<%= link_to "back", home_path %>

app/views/bundlr/users/edit.html.erb
<h1>Edit Profile</h1>

<%= form_for(@user) do |f| %>
	<%= render 'shared/error_messages' %>

	<%= f.label :email %>
	<%= f.text_field :email %>

	<%= f.label :password %>
	<%= f.text_field :password %>

	<%= f.label :password_confirmation %>
	<%= f.text_field :password_confirmation %>

	<%= f.label :avatar %>
	<%= f.file_field :avatar %>

	<%= f.submit "save changes" %>
<% end %>

app/views/bundlr/users/new.html.erb
<%= form_for(@user) do |f| %>

    <%= render 'shared/error_messages' %>
	
	<%= f.label :email %>
	<%= f.text_field :email %>

	<%= f.label :password %>
	<%= f.text_field :password %>

	<%= f.label :password_confirmation %>
	<%= f.text_field :password_confirmation %>

	<%= f.label :avatar %>
	<%= f.file_field :avatar %>

	<%= f.submit "create account", class: 'button' %>

<% end %>

app/views/bundlr/users/show.html.erb
<div class="six columns offset-by-five">

	<div id="home">

		<div class="squareButton green">
			<%= link_to "projects", projects_path %>
		</div>
		
		<div class="squareButton blue">bundles</div>

		<div class="welcome">Welcome, <%= @user.email %>!</div>

		<div class="squareButton orange">my profile</div>
		<div class="squareButton red">log out</div>

	</div>

</div>

app/views/layouts/bundlr/_header.html.erb
<div id="header">

	<%= image_tag "bundlr/shared/logoAlt.png", :class => 'logo' %>


	<% if signed_in? %>

		<%= link_to "settings", edit_user_path(current_user) %>
		<!-- <%= image_tag current_user.avatar.url(:thumb) %> -->
		<%= link_to current_user.email, current_user %>
		<%= link_to "sign out", signout_path, method: "delete" %>

	<% else %>
		You are not signed in
		<% link_to "sign in", signin_path %>
	<% end %>

</div>

app/views/layouts/bundlr/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bundlr</title>
  <%= stylesheet_link_tag    "bundlr/application", :media => "all" %>
  <%= javascript_include_tag "bundlr/application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/bundlr/header' %>

<div class="container">
	<%= render 'shared/flash_messages' %>
	<%= yield %>
</div>

<%= debug(params) if Rails.env.development? %>

</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>

	<% @user.errors.full_messages.each do |msg| %>
		<%= msg %>
	<% end %>

<% end %>

app/views/shared/_flash_messages.html.erb
<% if flash.any? %>
	<% flash.each do |key, value| %>
		<%= key %><%= value %>
	<% end %>
<% end %>